#!/bin/bash
# Run this as a script
sudo hostname docker
sudo apt update -y

# install docker and add ubuntu user to docker group 
sudo apt install docker.io -y
sudo usermod -aG docker ubuntu

# install java as jenkins dependency
sudo apt install openjdk-11-jdk -y

# import the GPG key
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

#  add the Jenkins software repository to the sources list and provide the key for authentication
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

sudo apt update -y

# install  and start jenkins
sudo apt install jenkins -y
sudo systemctl start jenkins
sudo systemctl enable jenkins

# grant jenkins user sudo access
sudo -i echo "jenkins  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/jenkins 

# add jenkins user to docker group and switch to jenkins user
sudo usermod -aG docker jenkins
sudo su - jenkins
